import os
import google.generativeai as genai
from google.api_core import exceptions
import json

class GeminiError(Exception):
    """Base exception for Gemini service errors."""
    def __init__(self, message, error_type="GeminiFailure"):
        self.message = message
        self.error_type = error_type
        super().__init__(self.message)

class MissingAPIKeyError(GeminiError):
    def __init__(self):
        super().__init__("Gemini API key is missing. Please configure GEMINI_API_KEY in your .env file.", "MissingAPIKey")

class InvalidAPIKeyError(GeminiError):
    def __init__(self):
        super().__init__("The provided Gemini API key is invalid. Please check your credentials.", "InvalidAPIKey")

class RateLimitError(GeminiError):
    def __init__(self):
        super().__init__("Gemini API rate limit exceeded. Please wait a moment before trying again.", "RateLimit")

class NetworkError(GeminiError):
    def __init__(self):
        super().__init__("Network error: Unable to reach Gemini services. Please check your internet connection.", "NoInternet")

class GeminiService:
    @staticmethod
    def get_api_key():
        return os.environ.get("GEMINI_API_KEY")

    @classmethod
    def _call_gemini(cls, system_instruction, prompt, response_mime_type=None):
        api_key = cls.get_api_key()
        if not api_key:
            raise MissingAPIKeyError()
        
        # Configure genai with the API key
        genai.configure(api_key=api_key)
        
        # Initialize model
        model = genai.GenerativeModel(
            model_name="gemini-3.5-flash",
            system_instruction=system_instruction
        )
        
        generation_config = {}
        if response_mime_type:
            generation_config["response_mime_type"] = response_mime_type

        try:
            response = model.generate_content(prompt, generation_config=generation_config)
            return response.text
        except exceptions.InvalidArgument as e:
            if "API key" in str(e) or "key" in str(e).lower() or "auth" in str(e).lower():
                raise InvalidAPIKeyError()
            raise GeminiError(f"Gemini API invalid argument: {str(e)}", "GeminiFailure")
        except exceptions.PermissionDenied as e:
            raise InvalidAPIKeyError()
        except exceptions.ResourceExhausted as e:
            raise RateLimitError()
        except exceptions.GoogleAPICallError as e:
            raise GeminiError(f"Gemini API error occurred: {str(e)}", "GeminiFailure")
        except Exception as e:
            err_str = str(e).lower()
            if "connection" in err_str or "socket" in err_str or "dns" in err_str or "unreachable" in err_str or "http" in err_str:
                raise NetworkError()
            raise GeminiError(f"An unexpected error occurred during Gemini call: {str(e)}", "GeminiFailure")

    @classmethod
    def generate_qa_response(cls, question, dataset_name, columns, summary_stats, patterns, chart_info):
        system_instruction = (
            "You are a professional AI Data Analyst. Your job is to answer user questions about a dataset.\n"
            "CRITICAL RULE: Never calculate statistics yourself. Python calculates everything. You must only explain the structured results generated by Python.\n"
            "Keep answers concise, clear, and professional. Use markdown tables, list items, bold text, and code blocks where appropriate."
        )
        
        prompt = (
            f"Dataset Name: {dataset_name}\n"
            f"Columns: {columns}\n"
            f"Summary Statistics: {json.dumps(summary_stats, indent=2)}\n"
            f"Detected Patterns: {json.dumps(patterns, indent=2)}\n"
            f"Chart Information: {json.dumps(chart_info, indent=2)}\n\n"
            f"User Question: {question}\n\n"
            f"Answer:"
        )
        
        return cls._call_gemini(system_instruction, prompt)

    @classmethod
    def generate_insights(cls, dataset_name, columns, summary_stats, patterns, chart_info):
        system_instruction = (
            "You are a professional AI Data Analyst. Generate a comprehensive dataset analysis. You must output the analysis in JSON format.\n"
            "The JSON output must have exactly the following keys:\n"
            "- 'executive_summary': A clear overview summarizing what this dataset represents.\n"
            "- 'key_findings': A list of key discoveries, trends, or observations from the data.\n"
            "- 'recommendations': A list of actionable recommendations for business/educational stakeholders.\n"
            "- 'potential_risks': A list of potential concerns, outliers, or data quality risks.\n"
            "- 'plain_english_explanation': A cohesive narrative explaining the dataset's context and meaning to non-technical readers.\n"
            "CRITICAL: Do not perform any calculations or create new statistics. Only explain the facts provided in the input context.\n"
            "Keep the responses clear, formatting list items using markdown if necessary, but keep the JSON values as strings or lists of strings."
        )
        
        prompt = (
            f"Dataset Name: {dataset_name}\n"
            f"Columns: {columns}\n"
            f"Summary Statistics: {json.dumps(summary_stats, indent=2)}\n"
            f"Detected Patterns: {json.dumps(patterns, indent=2)}\n"
            f"Chart Information: {json.dumps(chart_info, indent=2)}\n"
        )
        
        response_text = cls._call_gemini(system_instruction, prompt, response_mime_type="application/json")
        try:
            return json.loads(response_text)
        except Exception as e:
            raise GeminiError(f"Failed to parse insights response as JSON: {str(e)}", "GeminiFailure")

    @classmethod
    def generate_suggested_questions(cls, dataset_name, columns, summary_stats, patterns):
        """Generates exactly 3 context-aware suggested questions for the dataset using Gemini."""
        system_instruction = (
            "You are a Senior Data Analyst. Respond ONLY with a valid JSON array of exactly 3 strings. "
            "No extra text, no markdown, no explanations — only the JSON array. "
            "Each string must be a question under 12 words. "
            "The 3 questions must follow this exact order and type:\n"
            "1. A STATISTICAL question (e.g. average, total, max, min, count).\n"
            "2. An ANALYTICAL or TREND question (e.g. comparison, correlation, distribution, pattern).\n"
            "3. An AI INSIGHT or RECOMMENDATION question (e.g. summarize, recommend, predict, explain).\n"
            "Make every question highly specific to the dataset columns provided."
        )
        prompt = (
            f"Dataset Name: {dataset_name}\n"
            f"Columns: {columns}\n"
            f"Summary Statistics: {json.dumps(summary_stats)}\n"
            f"Detected Patterns: {json.dumps(patterns)}\n\n"
            "Return a JSON array of exactly 3 strings."
        )
        try:
            response_text = cls._call_gemini(system_instruction, prompt, response_mime_type="application/json")
            questions = json.loads(response_text)
            if isinstance(questions, list) and len(questions) >= 3:
                return [str(q) for q in questions[:3]]
        except Exception:
            pass
        return None

